//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace SmartPlayer.PlayerService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string NameField;
        
        private string LoginField;
        
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlayerService.MpServiceSoap")]
    public interface MpServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUser", ReplyAction="*")]
        System.Threading.Tasks.Task<SmartPlayer.PlayerService.GetUserResponse> GetUserAsync(SmartPlayer.PlayerService.GetUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindSong", ReplyAction="*")]
        System.Threading.Tasks.Task<SmartPlayer.PlayerService.FindSongResponse> FindSongAsync(SmartPlayer.PlayerService.FindSongRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindArtistId", ReplyAction="*")]
        System.Threading.Tasks.Task<SmartPlayer.PlayerService.FindArtistIdResponse> FindArtistIdAsync(SmartPlayer.PlayerService.FindArtistIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindAlbumId", ReplyAction="*")]
        System.Threading.Tasks.Task<SmartPlayer.PlayerService.FindAlbumIdResponse> FindAlbumIdAsync(SmartPlayer.PlayerService.FindAlbumIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindTitleId", ReplyAction="*")]
        System.Threading.Tasks.Task<SmartPlayer.PlayerService.FindTitleIdResponse> FindTitleIdAsync(SmartPlayer.PlayerService.FindTitleIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertArtist", ReplyAction="*")]
        System.Threading.Tasks.Task<SmartPlayer.PlayerService.InsertArtistResponse> InsertArtistAsync(SmartPlayer.PlayerService.InsertArtistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertAlbum", ReplyAction="*")]
        System.Threading.Tasks.Task<SmartPlayer.PlayerService.InsertAlbumResponse> InsertAlbumAsync(SmartPlayer.PlayerService.InsertAlbumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertTitle", ReplyAction="*")]
        System.Threading.Tasks.Task<SmartPlayer.PlayerService.InsertTitleResponse> InsertTitleAsync(SmartPlayer.PlayerService.InsertTitleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUser", Namespace="http://tempuri.org/", Order=0)]
        public SmartPlayer.PlayerService.GetUserRequestBody Body;
        
        public GetUserRequest() {
        }
        
        public GetUserRequest(SmartPlayer.PlayerService.GetUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUserRequestBody {
        
        public GetUserRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmartPlayer.PlayerService.GetUserResponseBody Body;
        
        public GetUserResponse() {
        }
        
        public GetUserResponse(SmartPlayer.PlayerService.GetUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SmartPlayer.PlayerService.User[] GetUserResult;
        
        public GetUserResponseBody() {
        }
        
        public GetUserResponseBody(SmartPlayer.PlayerService.User[] GetUserResult) {
            this.GetUserResult = GetUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindSongRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindSong", Namespace="http://tempuri.org/", Order=0)]
        public SmartPlayer.PlayerService.FindSongRequestBody Body;
        
        public FindSongRequest() {
        }
        
        public FindSongRequest(SmartPlayer.PlayerService.FindSongRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindSongRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string album;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string artist;
        
        public FindSongRequestBody() {
        }
        
        public FindSongRequestBody(string title, string album, string artist) {
            this.title = title;
            this.album = album;
            this.artist = artist;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindSongResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindSongResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmartPlayer.PlayerService.FindSongResponseBody Body;
        
        public FindSongResponse() {
        }
        
        public FindSongResponse(SmartPlayer.PlayerService.FindSongResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindSongResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool FindSongResult;
        
        public FindSongResponseBody() {
        }
        
        public FindSongResponseBody(bool FindSongResult) {
            this.FindSongResult = FindSongResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindArtistIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindArtistId", Namespace="http://tempuri.org/", Order=0)]
        public SmartPlayer.PlayerService.FindArtistIdRequestBody Body;
        
        public FindArtistIdRequest() {
        }
        
        public FindArtistIdRequest(SmartPlayer.PlayerService.FindArtistIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindArtistIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string artist;
        
        public FindArtistIdRequestBody() {
        }
        
        public FindArtistIdRequestBody(string artist) {
            this.artist = artist;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindArtistIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindArtistIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmartPlayer.PlayerService.FindArtistIdResponseBody Body;
        
        public FindArtistIdResponse() {
        }
        
        public FindArtistIdResponse(SmartPlayer.PlayerService.FindArtistIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindArtistIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Nullable<int> FindArtistIdResult;
        
        public FindArtistIdResponseBody() {
        }
        
        public FindArtistIdResponseBody(System.Nullable<int> FindArtistIdResult) {
            this.FindArtistIdResult = FindArtistIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindAlbumIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindAlbumId", Namespace="http://tempuri.org/", Order=0)]
        public SmartPlayer.PlayerService.FindAlbumIdRequestBody Body;
        
        public FindAlbumIdRequest() {
        }
        
        public FindAlbumIdRequest(SmartPlayer.PlayerService.FindAlbumIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindAlbumIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string album;
        
        public FindAlbumIdRequestBody() {
        }
        
        public FindAlbumIdRequestBody(string album) {
            this.album = album;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindAlbumIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindAlbumIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmartPlayer.PlayerService.FindAlbumIdResponseBody Body;
        
        public FindAlbumIdResponse() {
        }
        
        public FindAlbumIdResponse(SmartPlayer.PlayerService.FindAlbumIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindAlbumIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Nullable<int> FindAlbumIdResult;
        
        public FindAlbumIdResponseBody() {
        }
        
        public FindAlbumIdResponseBody(System.Nullable<int> FindAlbumIdResult) {
            this.FindAlbumIdResult = FindAlbumIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindTitleIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindTitleId", Namespace="http://tempuri.org/", Order=0)]
        public SmartPlayer.PlayerService.FindTitleIdRequestBody Body;
        
        public FindTitleIdRequest() {
        }
        
        public FindTitleIdRequest(SmartPlayer.PlayerService.FindTitleIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindTitleIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        public FindTitleIdRequestBody() {
        }
        
        public FindTitleIdRequestBody(string title) {
            this.title = title;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindTitleIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindTitleIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmartPlayer.PlayerService.FindTitleIdResponseBody Body;
        
        public FindTitleIdResponse() {
        }
        
        public FindTitleIdResponse(SmartPlayer.PlayerService.FindTitleIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindTitleIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Nullable<int> FindTitleIdResult;
        
        public FindTitleIdResponseBody() {
        }
        
        public FindTitleIdResponseBody(System.Nullable<int> FindTitleIdResult) {
            this.FindTitleIdResult = FindTitleIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertArtistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertArtist", Namespace="http://tempuri.org/", Order=0)]
        public SmartPlayer.PlayerService.InsertArtistRequestBody Body;
        
        public InsertArtistRequest() {
        }
        
        public InsertArtistRequest(SmartPlayer.PlayerService.InsertArtistRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertArtistRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string artist;
        
        public InsertArtistRequestBody() {
        }
        
        public InsertArtistRequestBody(string artist) {
            this.artist = artist;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertArtistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertArtistResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmartPlayer.PlayerService.InsertArtistResponseBody Body;
        
        public InsertArtistResponse() {
        }
        
        public InsertArtistResponse(SmartPlayer.PlayerService.InsertArtistResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertArtistResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertArtistResult;
        
        public InsertArtistResponseBody() {
        }
        
        public InsertArtistResponseBody(bool InsertArtistResult) {
            this.InsertArtistResult = InsertArtistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertAlbumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertAlbum", Namespace="http://tempuri.org/", Order=0)]
        public SmartPlayer.PlayerService.InsertAlbumRequestBody Body;
        
        public InsertAlbumRequest() {
        }
        
        public InsertAlbumRequest(SmartPlayer.PlayerService.InsertAlbumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertAlbumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string album;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<int> artistId;
        
        public InsertAlbumRequestBody() {
        }
        
        public InsertAlbumRequestBody(string album, System.Nullable<int> artistId) {
            this.album = album;
            this.artistId = artistId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertAlbumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertAlbumResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmartPlayer.PlayerService.InsertAlbumResponseBody Body;
        
        public InsertAlbumResponse() {
        }
        
        public InsertAlbumResponse(SmartPlayer.PlayerService.InsertAlbumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertAlbumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertAlbumResult;
        
        public InsertAlbumResponseBody() {
        }
        
        public InsertAlbumResponseBody(bool InsertAlbumResult) {
            this.InsertAlbumResult = InsertAlbumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertTitleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertTitle", Namespace="http://tempuri.org/", Order=0)]
        public SmartPlayer.PlayerService.InsertTitleRequestBody Body;
        
        public InsertTitleRequest() {
        }
        
        public InsertTitleRequest(SmartPlayer.PlayerService.InsertTitleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertTitleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string artist;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<int> albumId;
        
        public InsertTitleRequestBody() {
        }
        
        public InsertTitleRequestBody(string artist, System.Nullable<int> albumId) {
            this.artist = artist;
            this.albumId = albumId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertTitleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertTitleResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmartPlayer.PlayerService.InsertTitleResponseBody Body;
        
        public InsertTitleResponse() {
        }
        
        public InsertTitleResponse(SmartPlayer.PlayerService.InsertTitleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertTitleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertTitleResult;
        
        public InsertTitleResponseBody() {
        }
        
        public InsertTitleResponseBody(bool InsertTitleResult) {
            this.InsertTitleResult = InsertTitleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MpServiceSoapChannel : SmartPlayer.PlayerService.MpServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MpServiceSoapClient : System.ServiceModel.ClientBase<SmartPlayer.PlayerService.MpServiceSoap>, SmartPlayer.PlayerService.MpServiceSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MpServiceSoapClient() : 
                base(MpServiceSoapClient.GetDefaultBinding(), MpServiceSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.MpServiceSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MpServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(MpServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), MpServiceSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MpServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MpServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MpServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MpServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MpServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmartPlayer.PlayerService.GetUserResponse> SmartPlayer.PlayerService.MpServiceSoap.GetUserAsync(SmartPlayer.PlayerService.GetUserRequest request) {
            return base.Channel.GetUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartPlayer.PlayerService.GetUserResponse> GetUserAsync() {
            SmartPlayer.PlayerService.GetUserRequest inValue = new SmartPlayer.PlayerService.GetUserRequest();
            inValue.Body = new SmartPlayer.PlayerService.GetUserRequestBody();
            return ((SmartPlayer.PlayerService.MpServiceSoap)(this)).GetUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmartPlayer.PlayerService.FindSongResponse> SmartPlayer.PlayerService.MpServiceSoap.FindSongAsync(SmartPlayer.PlayerService.FindSongRequest request) {
            return base.Channel.FindSongAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartPlayer.PlayerService.FindSongResponse> FindSongAsync(string title, string album, string artist) {
            SmartPlayer.PlayerService.FindSongRequest inValue = new SmartPlayer.PlayerService.FindSongRequest();
            inValue.Body = new SmartPlayer.PlayerService.FindSongRequestBody();
            inValue.Body.title = title;
            inValue.Body.album = album;
            inValue.Body.artist = artist;
            return ((SmartPlayer.PlayerService.MpServiceSoap)(this)).FindSongAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmartPlayer.PlayerService.FindArtistIdResponse> SmartPlayer.PlayerService.MpServiceSoap.FindArtistIdAsync(SmartPlayer.PlayerService.FindArtistIdRequest request) {
            return base.Channel.FindArtistIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartPlayer.PlayerService.FindArtistIdResponse> FindArtistIdAsync(string artist) {
            SmartPlayer.PlayerService.FindArtistIdRequest inValue = new SmartPlayer.PlayerService.FindArtistIdRequest();
            inValue.Body = new SmartPlayer.PlayerService.FindArtistIdRequestBody();
            inValue.Body.artist = artist;
            return ((SmartPlayer.PlayerService.MpServiceSoap)(this)).FindArtistIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmartPlayer.PlayerService.FindAlbumIdResponse> SmartPlayer.PlayerService.MpServiceSoap.FindAlbumIdAsync(SmartPlayer.PlayerService.FindAlbumIdRequest request) {
            return base.Channel.FindAlbumIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartPlayer.PlayerService.FindAlbumIdResponse> FindAlbumIdAsync(string album) {
            SmartPlayer.PlayerService.FindAlbumIdRequest inValue = new SmartPlayer.PlayerService.FindAlbumIdRequest();
            inValue.Body = new SmartPlayer.PlayerService.FindAlbumIdRequestBody();
            inValue.Body.album = album;
            return ((SmartPlayer.PlayerService.MpServiceSoap)(this)).FindAlbumIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmartPlayer.PlayerService.FindTitleIdResponse> SmartPlayer.PlayerService.MpServiceSoap.FindTitleIdAsync(SmartPlayer.PlayerService.FindTitleIdRequest request) {
            return base.Channel.FindTitleIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartPlayer.PlayerService.FindTitleIdResponse> FindTitleIdAsync(string title) {
            SmartPlayer.PlayerService.FindTitleIdRequest inValue = new SmartPlayer.PlayerService.FindTitleIdRequest();
            inValue.Body = new SmartPlayer.PlayerService.FindTitleIdRequestBody();
            inValue.Body.title = title;
            return ((SmartPlayer.PlayerService.MpServiceSoap)(this)).FindTitleIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmartPlayer.PlayerService.InsertArtistResponse> SmartPlayer.PlayerService.MpServiceSoap.InsertArtistAsync(SmartPlayer.PlayerService.InsertArtistRequest request) {
            return base.Channel.InsertArtistAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartPlayer.PlayerService.InsertArtistResponse> InsertArtistAsync(string artist) {
            SmartPlayer.PlayerService.InsertArtistRequest inValue = new SmartPlayer.PlayerService.InsertArtistRequest();
            inValue.Body = new SmartPlayer.PlayerService.InsertArtistRequestBody();
            inValue.Body.artist = artist;
            return ((SmartPlayer.PlayerService.MpServiceSoap)(this)).InsertArtistAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmartPlayer.PlayerService.InsertAlbumResponse> SmartPlayer.PlayerService.MpServiceSoap.InsertAlbumAsync(SmartPlayer.PlayerService.InsertAlbumRequest request) {
            return base.Channel.InsertAlbumAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartPlayer.PlayerService.InsertAlbumResponse> InsertAlbumAsync(string album, System.Nullable<int> artistId) {
            SmartPlayer.PlayerService.InsertAlbumRequest inValue = new SmartPlayer.PlayerService.InsertAlbumRequest();
            inValue.Body = new SmartPlayer.PlayerService.InsertAlbumRequestBody();
            inValue.Body.album = album;
            inValue.Body.artistId = artistId;
            return ((SmartPlayer.PlayerService.MpServiceSoap)(this)).InsertAlbumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmartPlayer.PlayerService.InsertTitleResponse> SmartPlayer.PlayerService.MpServiceSoap.InsertTitleAsync(SmartPlayer.PlayerService.InsertTitleRequest request) {
            return base.Channel.InsertTitleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartPlayer.PlayerService.InsertTitleResponse> InsertTitleAsync(string artist, System.Nullable<int> albumId) {
            SmartPlayer.PlayerService.InsertTitleRequest inValue = new SmartPlayer.PlayerService.InsertTitleRequest();
            inValue.Body = new SmartPlayer.PlayerService.InsertTitleRequestBody();
            inValue.Body.artist = artist;
            inValue.Body.albumId = albumId;
            return ((SmartPlayer.PlayerService.MpServiceSoap)(this)).InsertTitleAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.MpServiceSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.MpServiceSoap)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:55573/MPService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return MpServiceSoapClient.GetBindingForEndpoint(EndpointConfiguration.MpServiceSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return MpServiceSoapClient.GetEndpointAddress(EndpointConfiguration.MpServiceSoap);
        }
        
        public enum EndpointConfiguration {
            
            MpServiceSoap,
        }
    }
}
